### ISSUE TITLE
Sentinel ignores supplied resolution

### ISSUE THREAD

**Issue by SteffenCucos** [lennart-rth/Live-Earth-Wallpapers#12]
**Describe the bug**
Sentinel code does not use supplied resolution when loading images from url

**To Reproduce**

**Expected behavior**
We should pass the args.width/height to the sentinel satellite url

**Screenshots**
```
def calcImageDimensions(args):
    pixelWidth = 1920
    if args.width is not None and args.height is not None:
        pixelHeight = pixelWidth / (args.width/args.height)
    else:
        pixelHeight = pixelWidth / (16/9)

    return int(pixelWidth), int(pixelHeight) # ALWAYS RETURNS 1920 WIDTH
 ```
 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lennart-rth** [comment]
This is done. By specifying -w -he. You can also download custom image sizes for different monitors now
