### ISSUE TITLE
goes-17 imagery fails to download

### ISSUE THREAD

**Issue by vszabo2** [lennart-rth/Live-Earth-Wallpapers#3]
It says "Could not download Image 'https://rammb-slider.cira.colostate.edu/data/imagery/2022/11/05/goes-17---full_disk/natural_color/20221104122032/03/000_000.png'"

Other sources are working for me.

Specific command and full output is [here](https://github.com/lennart-rth/Live-Earth-Wallpapers/files/9944629/goes-17-output.txt).

**Comment by lennart-rth** [comment]
Unfortunately this is a problem out of my scope! The image URL is perfectly correct. 
Goes-17 images just did not update for the last few hours. Wait a day and this will probably be working again!
Possible Solution:
I already implemented a 3 hour delay to prevent irregularities in the upload cycle. (At 16:00 it will download the image from 13:00)
This delay could be increased if goes-17 shows to be unreliable in the future.
