### ISSUE TITLE
Can't set time to switch

### ISSUE THREAD

**Issue by WinKevin66** [lennart-rth/Live-Earth-Wallpapers#41]
Hi, 

I can switch wallpaper by manual, but can't 'create new scheduler', and the status always is 'Not running'.

On this picture, what i only can do is 'Test now', and it can go, but other three are not working.

Thank you for your reply!

![wechat_2024-10-16_093022_709](https://github.com/user-attachments/assets/c22ca488-e83c-4705-b1b4-d84420944050)

**Comment by WinKevin66** [comment]
Sorry for not telling about environment, I use it on Linux with 'pop!OS', my desktop environment is 'pop:GNOME'

**Comment by lennart-rth** [comment]
Hi, sounds like there is a problem with systemctl (the scheduler).
Can you try and click on "new schedule" and then see if it has been created? (`sudo systemctl status liewa.service` or `systemctl --user status liewa.service`or `journalctl -u liewa.service`).

If not you can try to set it up manually and see why or where it fails:
`sudo nano /etc/systemd/system/liewa.service` with the following:
```[Unit]
Description=Liewa Service

[Service]
Type=simple
ExecStart=/bin/bash liewa-cli

[Install]
WantedBy=graphical.target
```
 2. `sudo nano /etc/systemd/system/liewa.timer` with the following:
 ```[Unit]
Description=Liewa Timer

[Timer]
OnCalendar=*-*-* *:00:00

[Install]
WantedBy=timers.target
```

3.  Then do:
`sudo systemctl daemon-reload`,
`sudo systemctl enable liewa.timer`,
`sudo systemctl start liewa.timer`,
`sudo systemctl start liewa.service` etc.
Check the status with `sudo systemctl status liewa.service` again. What is the output?


You can remove the service with `systemctl stop`, `disable` and deleting the liewa.service and liewa.timer files.

**Comment by WinKevin66** [comment]
Hi, 
I got it!
I found that, `liewa.service` and `liewa.timer` don't appear in  `/etc/systemd/system/`, but in `/opt/liewa/_internal/liewa`, then I copy them to first directory and modify something, fellow the steps you said,  it's running!!Thank you!!
